version: "3.8"

services:
  backend:
    build: .
    container_name: backend-library
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads # Permet de sauvegarder les fichiers uploadés

  mongodb:
    image: mongo:6
    container_name: mongodb-library
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
